const admin = [
  {
    id: 1,
    firstName: "John",
    email: "admin@me.com",
    password: "123",
  },
];
const employees = [
  {
    id: 1,
    firstName: "Rohan",
    email: "e@e.com",
    password: "123",
    attendance: {
      presentDays: 20,
      absentDays: 2,
      leavesLeft: 5,
      halfDayLeaves: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Complete Project Proposal",
        description: "Draft the project proposal for the new client.",
        dueDate: "2024-10-25",
        category: "Project Management",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Update Team on Progress",
        description: "Send an email update to the team about the project.",
        dueDate: "2024-10-20",
        category: "Communication",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: true,
        title: "Research Competitors",
        description: "Analyze the top three competitors in our market.",
        dueDate: "2024-10-30",
        category: "Research",
      },
    ],
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 2,
    firstName: "Ashu",
    email: "employee2@example.com",
    password: "123",
    attendance: {
      presentDays: 22,
      absentDays: 1,
      leavesLeft: 4,
      halfDayLeaves: 0,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Client Meeting Preparation",
        description: "Prepare the agenda and materials for the client meeting.",
        dueDate: "2024-10-22",
        category: "Meeting",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Design Mockups",
        description: "Create design mockups for the new website.",
        dueDate: "2024-10-15",
        category: "Design",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: true,
        title: "Write Blog Post",
        description: "Draft a blog post about our recent success.",
        dueDate: "2024-10-28",
        category: "Content",
      },
    ],
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 3,
    firstName: "Amit",
    email: "employee3@example.com",
    password: "123",
    attendance: {
      presentDays: 21,
      absentDays: 2,
      leavesLeft: 3,
      halfDayLeaves: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Team Building Activity",
        description: "Organize a team-building activity for the department.",
        dueDate: "2024-10-29",
        category: "Event",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Submit Expense Reports",
        description: "Complete and submit all outstanding expense reports.",
        dueDate: "2024-10-18",
        category: "Finance",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Conduct Training Session",
        description: "Prepare and conduct a training session for new hires.",
        dueDate: "2024-10-26",
        category: "Training",
      },
    ],
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 4,
    firstName: "Riya",
    email: "employee4@example.com",
    password: "123",
    attendance: {
      presentDays: 20,
      absentDays: 3,
      leavesLeft: 2,
      halfDayLeaves: 1,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Develop Marketing Strategy",
        description:
          "Create a comprehensive marketing strategy for the upcoming quarter.",
        dueDate: "2024-10-31",
        category: "Marketing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Update Website Content",
        description: "Revise the content on the website for better SEO.",
        dueDate: "2024-10-12",
        category: "Content",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: true,
        title: "Analyze Customer Feedback",
        description:
          "Review and analyze customer feedback from the last survey.",
        dueDate: "2024-10-25",
        category: "Analysis",
      },
    ],
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 5,
    firstName: "Ava",
    email: "employee5@example.com",
    password: "123",
    attendance: {
      presentDays: 22,
      absentDays: 1,
      leavesLeft: 4,
      halfDayLeaves: 0,
    },
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Create Sales Report",
        description:
          "Compile the sales data and create a report for the quarterly review.",
        dueDate: "2024-10-24",
        category: "Sales",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Inventory Check",
        description: "Conduct an inventory check of all office supplies.",
        dueDate: "2024-10-10",
        category: "Inventory",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: true,
        title: "Prepare Financial Statements",
        description: "Prepare the financial statements for the last quarter.",
        dueDate: "2024-10-27",
        category: "Finance",
      },
    ],
    taskCounts: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
  },
];
export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};
export const getLocalStorage = () => {
  const empData = JSON.parse(localStorage.getItem("employees"));
  const admData = JSON.parse(localStorage.getItem("admin"));
  return { empData, admData };
};
